# Always-Sync Configuration
# These files are synced on EVERY run and OVERWRITE existing files
#
# NOTE: CI/CD workflows are in initial-only/ because each game has unique build needs.
# Only AI workflows, cursor rules, and agents are synced always.
#
# Documentation: https://github.com/BetaHuhn/repo-file-sync-action

group:
  # ============================================================================
  # Core files - synced to ALL repositories
  # AI workflows, cursor rules, agents - NOT ci/cd (games are unique)
  # ============================================================================
  - files:
      # Cursor rules (always overwrite)
      - source: repository-files/always-sync/.cursor/rules/
        dest: .cursor/rules/
        deleteOrphaned: true
      # GitHub workflows - AI and ecosystem workflows only (no ci/cd)
      - source: repository-files/always-sync/.github/workflows/
        dest: .github/workflows/
        deleteOrphaned: false
      # GitHub agents
      - source: repository-files/always-sync/.github/agents/
        dest: .github/agents/
        deleteOrphaned: true
      # Documentation base
      - source: repository-files/always-sync/docs/README.md
        dest: docs/README.md
    repos: &all_repos |
      arcade-cabinet/otter-elite-force
      arcade-cabinet/dragons-labyrinth
      arcade-cabinet/ebb-and-bloom
      arcade-cabinet/realm-walker
      arcade-cabinet/rivers-of-reckoning
      arcade-cabinet/otter-river-rush
      arcade-cabinet/protocol-silent-night
      arcade-cabinet/rivermarsh
      arcade-cabinet/echoes-of-beastlight
      arcade-cabinet/cosmic-cults
      arcade-cabinet/otterblade-odyssey
